# vim: syntax=ruby filetype=ruby
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'ldez/tap'

# System tools
brew 'gettext'
brew 'proctools'
brew 'pstree'
brew 'coreutils'
brew 'findutils'
brew 'htop'
brew 'gnu-tar'
brew 'gnu-time'
brew 'gnu-which'
brew 'gnu-sed'
brew 'gnu-indent'
brew 'grep'
brew 'gawk'
brew 'gnutls'
brew 'gnu-getopt'
brew 'parallel'
brew 'screen'
brew 'ncurses'
brew 'pv'
brew 'unrar'
brew 'shfmt'

# Development & Power Tools
cask 'iterm2'
cask 'visual-studio-code'
cask 'goland'
brew 'bash'
brew 'bash-completion'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'ack'
brew 'ccat'
brew 'icdiff'
brew 'diff-so-fancy'
brew 'git' # no force-bottle: git --exec-path doesn't work, remote helpers missing from path
brew 'gti'
brew 'prm'
brew 'go'
brew 'fzf'
brew 'grv'
brew 'hub'
brew 'jq'
brew 'node'
brew 'rust'
brew 'ruby'
brew 'python2'
brew 'python3'
brew 'openssl'
brew 'openssh'
brew 'protobuf'
brew 'prototool'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'tree'
brew 'wget'
cask 'google-cloud-sdk'
brew 'watch'
brew 'fd'
brew 'ncdu'
brew 'wdiff'
brew 'entr'
brew 'bats'
brew 'tldr'
brew 'hugo'
brew 'shellcheck'
brew 'telnet'
brew 'mitmproxy'
brew 'fortio'

# Commit signing
brew 'pinentry-mac'
brew 'gnupg'
cask 'keybase'

# Containers
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'kubectx'
brew 'kube-ps1'
cask 'minikube'
brew 'docker-machine-driver-hyperkit'
brew 'skaffold'
brew 'kustomize'
brew 'cfssl'
cask 'docker' # docker for desktop

# Fun tools
brew 'asciinema'
brew 'lolcat'

# kubernetes dev
brew 'hg'
brew 'etcd'

# Desktop Software
cask 'clipy'
cask 'recordit'
cask 'zoomus'
cask 'flux'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask '1password'
cask 'dropbox'
cask 'google-chrome'
cask 'coconutbattery'
cask 'firefox'
cask 'open-in-code'
