# vim: syntax=ruby filetype=ruby
tap 'ldez/tap'
tap 'sigstore/tap'
tap 'homeport/tap' # dyff

# System tools
brew 'gettext'
brew 'proctools'
brew 'pstree'
brew 'coreutils'
brew 'findutils'
brew 'htop'
brew 'gnu-tar'
brew 'gnu-time'
brew 'gnu-which'
brew 'gnu-sed'
brew 'gnu-indent'
brew 'grep'
brew 'less'
brew 'gawk'
brew 'gnutls'
brew 'gnu-getopt'
brew 'parallel'
brew 'screen'
brew 'ncurses'
brew 'pv'
brew 'shfmt'
brew 'ncdu'
brew 'dust'
brew 'z'

# Development & Power Tools
cask 'iterm2'
cask 'visual-studio-code'
cask 'goland'
brew 'bash'
brew 'bash-completion'
brew 'ghostty'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'oh-my-posh'
brew 'ack'
brew 'ccat'
brew 'bat'
brew 'icdiff'
brew 'colordiff'
brew 'diff-so-fancy'
brew 'difftastic'
brew 'git-delta'
brew 'dyff'
brew 'git' # no force-bottle: git --exec-path doesn't work, remote helpers missing from path
brew 'gitsign'
brew 'gh'
brew 'hg'
brew 'interactive-rebase-tool'
brew 'gti'
brew 'prm'
brew 'mkcert'
brew 'step'
brew 'go'
brew 'fzf'
brew 'grv'
brew 'jq'
brew 'jless'
brew 'node'
brew 'rust'
brew 'ruby'
brew 'python3'
brew 'openssl'
brew 'openssh'
brew 'protobuf'
brew 'prototool'
brew 'dog'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'tree'
brew 'wget'
brew 'watch'
brew 'fd'
brew 'wdiff'
brew 'entr'
brew 'direnv'
brew 'bats'
brew 'tldr'
brew 'hugo'
brew 'shellcheck'
brew 'telnet'
brew 'mitmproxy'
brew 'fortio'

# Commit signing
brew 'pinentry-mac'
brew 'gnupg'
cask 'keybase'

# Containers
brew 'kubernetes-cli'
brew 'helm'
brew 'kubectx'
brew 'kube-ps1'
brew 'kind'
brew 'skaffold'
brew 'kustomize'
brew 'cfssl'
cask 'docker-desktop'
brew 'ko'
brew 'dive'
brew 'crane'
brew 'cosign'

# Fun tools
brew 'asciinema'
brew 'lolcat'


# Desktop Software
cask 'maccy'
cask 'jordanbaird-ice'
cask 'vimac'
cask 'zoomus'
# cask 'slack'
# cask 'rectangle' # we use pro
cask 'monitorcontrol'
cask 'spotify'
cask '1password'
# cask 'dropbox'
# cask 'google-chrome'
# cask 'firefox'
cask 'discord'

# Hardware support
brew 'ykman'

# Streaming software
cask 'obs'
cask 'vlc'
