# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
"$schema": https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
console_title_template: "{{ .Shell }} in {{ .Folder }}"
final_space: true

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: iterm
        interactive: true
        style: plain
        foreground: "#80ffea"
        template: "{{ .PromptMark }}"

      - type: kubectl
        properties:
          cache_timeout: 0
        style: powerline
        # powerline_symbol: "⎈ "
        template: "<b>{{.Context}}</b>{{with .Namespace}}{{if not (eq . \"default\")}}:{{abbrev 25 .}}{{end}}{{end}}"
        foreground: "#C6FF00"
        background: "#33691E"
        background_templates:
        - '{{if or (contains "prod" .Context) (contains "grid" .Context) }}#B71C1C{{end}}'
        - '{{if hasPrefix "ei" .Context }}#30336b{{end}}'
        foreground_templates:
        - '{{if or (contains "prod" .Context) (contains "grid" .Context) }}#FFCDD2{{end}}'
        - '{{if hasPrefix "ei" .Context }}#FFFFFF{{end}}'

      - type: git
        style: powerline
        background: "#fffb38"
        background_templates:
        - "{{ if or (.Working.Changed) (.Staging.Changed) }}#bdc810{{ end }}"
        - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}"
        - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
        - "{{ if gt .Behind 0 }}#B388FF{{ end }}"
        foreground: "#193549"
        powerline_symbol: ""
        properties:
          branch_max_length: 35
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        template: >
          {{ .UpstreamIcon }}{{ .HEAD }}
          {{- if .BranchStatus }} {{ .BranchStatus }}{{ end }}
          {{- if .Working.Changed }}  {{ .Working.String }}{{ end -}}
          {{- if and (.Working.Changed) (.Staging.Changed) }}{{ end -}}
          {{- if .Staging.Changed }}  {{ .Staging.String }}{{ end -}}

      - type: path
        style: powerline
        powerline_symbol: ""
        foreground: "#ffffff"
        background: "#448AFF"
        properties:
          home_icon: "\uf015"
          style: "folder"

      - type: executiontime
        style: powerline
        background: "#83769c"
        foreground: "#ffffff"
        powerline_symbol: ""
        properties:
          threshold: 500
        template: "  {{ .FormattedMs }}"

      - type: status
        style: powerline
        foreground: "#ffffff"
        background: "#00897b"
        powerline_symbol: ""
        background_templates:
          - "{{ if .Error }}#e91e63{{ end }}"
        template: "{{ if and (.Error) (and (ne .Code 130) (ne .Code 0))}} \uea87 {{.Code}}{{ end }}"
