# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
"$schema": https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
console_title_template: "{{ .Shell }} in {{ .Folder }}"
final_space: true

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: iterm
        interactive: true
        style: plain
        foreground: "#80ffea"
        template: "{{ .PromptMark }}"

      - type: kubectl
        style: powerline
        powerline_symbol: "⎈ "
        template: "{{.Context}}{{with .Namespace}}:{{abbrev 12 .}}{{end}}"
        foreground: "#000000"
        background: "#FFA000"
        background_templates:
        - '{{ if or (contains . "prod") (contains . "grid")}}red{{end}}'

      - type: git
        style: powerline
        background: "#fffb38"
        background_templates:
        - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}"
        - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}"
        - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
        - "{{ if gt .Behind 0 }}#B388FF{{ end }}"
        foreground: "#193549"
        powerline_symbol: ""
        properties:
          branch_max_length: 25
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        template: >
          {{ .UpstreamIcon }}{{ .HEAD }}
          {{- if .BranchStatus }} {{ .BranchStatus }}{{ end }}
          {{- if .Working.Changed }}  {{ .Working.String }}{{ end -}}
          {{- if and (.Working.Changed) (.Staging.Changed) }}{{ end -}}
          {{- if .Staging.Changed }}  {{ .Staging.String }}{{ end -}}

      - type: path
        style: powerline
        powerline_symbol: ""
        foreground: "#ffffff"
        background: "#448AFF"
        properties:
          home_icon: "\uf015"
          style: "folder"

      - type: executiontime
        style: powerline
        background: "#83769c"
        foreground: "#ffffff"
        powerline_symbol: ""
        properties:
          threshold: 500
        template: "  {{ .FormattedMs }}"

      - type: status
        style: powerline
        foreground: "#ffffff"
        background: "#00897b"
        powerline_symbol: ""
        background_templates:
          - "{{ if .Error }}#e91e63{{ end }}"
        template: " \uea87 "
